language: node_js
node_js: node
cache: yarn
jobs:
  include:
  - stage: Test
    script: yarn test
  - stage: Size
    before_script: yarn build
    script: yarn size
  - stage: Release
    if: tag =~ ^v[0-9]
    env: NPM_TAG=$([[ "$TRAVIS_TAG" == *-* ]] && echo "next" || echo "latest")
    script: echo "Releasing $TRAVIS_TAG to npm with tag \"$NPM_TAG\" ..."
    deploy:
      provider: npm
      skip_cleanup: true
      tag: "$NPM_TAG"
      email: npm@mjackson.me
      api_key: "$NPM_TOKEN"
      on:
        tags: true
