sudo: false
language: node_js
node_js: node
cache: npm
env:
- TEST_ENV=cjs BUILD_ENV=cjs
- TEST_ENV=umd BUILD_ENV=umd
- TEST_ENV=source
before_script:
- ([[ -z "$BUILD_ENV" ]] || npm run build)
script:
- npm run lint
- npm test
